name: Daily Native Updates

on:
  schedule:
    - cron: '0 0 * * *'  # midnight
  workflow_dispatch:      # manually
    inputs:
      simulate:
        description: 'Simulate changes'
        required: false
        type: boolean
        default: false

jobs:
  update-natives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Setup initial files
        run: |
          mkdir -p original_plugin
          cp -r plugin/* original_plugin/
          
      - name: Build and Run
        id: run
        run: |
          if [[ "${{ inputs.simulate }}" == "true" ]]; then
            cargo run --release -- --simulate-change > changes.txt
          else
            cargo run --release > changes.txt
          fi
          echo "CHANGES<<EOF" >> $GITHUB_ENV
          cat changes.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Check for changes
        id: check
        run: |
          echo "Diff content:"
          diff -r original_plugin plugin || true
          echo "-------------------"
          
          echo "Original GTA5:"
          cat original_plugin/json/gta5/natives.json | head -n 20
          echo "-------------------"
          echo "New GTA5:"
          cat plugin/json/gta5/natives.json | head -n 20
          echo "-------------------"
          
          echo "Original RDR3:"
          cat original_plugin/json/rdr3/natives.json | head -n 20
          echo "-------------------"
          echo "New RDR3:"
          cat plugin/json/rdr3/natives.json | head -n 20
          echo "-------------------"
          
          # Vérifier les différences pour les deux jeux
          diff -r original_plugin/json/gta5 plugin/json/gta5 || true
          diff -r original_plugin/json/rdr3 plugin/json/rdr3 || true
          
          # Si l'un des deux a des différences, marquer comme changé
          if ! diff -r original_plugin/json/gta5 plugin/json/gta5 > /dev/null 2>&1 || \
             ! diff -r original_plugin/json/rdr3 plugin/json/rdr3 > /dev/null 2>&1; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate branch name
        if: steps.check.outputs.changes == 'true'
        id: branch
        run: |
          timestamp=$(date +%Y%m%d-%H%M%S)
          echo "name=update/natives-data-${timestamp}" >> $GITHUB_OUTPUT

      - name: Prepare for PR
        if: steps.check.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          echo "changes.txt" >> .gitignore
          echo "original_plugin/" >> .gitignore
          echo "fetched/" >> .gitignore
          echo "target/" >> .gitignore
          
          git add plugin/
          git add .gitignore
          
      - name: Create Pull Request
        if: steps.check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore: update natives data"
          title: "${{ inputs.simulate && '🧪 Test - ' || '🤖 ' }}Daily Natives Update"
          body: |
            ## Detected Changes
            
            ${{ inputs.simulate && '⚠️ This is a simulation of changes ⚠️\n\n' || '' }}
            ```
            ${{ env.CHANGES }}
            ```
            
            This PR was automatically generated by the daily update workflow.
          branch: ${{ steps.branch.outputs.name }}
          base: main
          delete-branch: true
          labels: |
            automated pr
            natives update
            ${{ inputs.simulate && 'simulation' || '' }}

      - name: Check PR Status
        if: steps.check.outputs.changes == 'true'
        run: |
          echo "Pull Request created successfully on branch ${{ steps.branch.outputs.name }}"
          echo "The changes have been detected and documented in the PR" 